# Generated by Django 4.2.9 on 2024-01-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_applications', '0002_leaveapplication_is_actedon'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='consumed_dayss',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
