# Generated by Django 4.2.9 on 2024-01-12 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_applications', '0003_leaveapplication_consumed_dayss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveapplication',
            old_name='consumed_dayss',
            new_name='consumed_days',
        ),
    ]
