# Generated by Django 4.2.9 on 2024-01-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_applications', '0004_rename_consumed_dayss_leaveapplication_consumed_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='consumed_days',
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
