# Generated by Django 4.2.9 on 2024-01-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_applications', '0005_remove_leaveapplication_consumed_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
