# Generated by Django 4.2.9 on 2024-01-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_applications', '0006_alter_leaveapplication_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
