# Generated by Django 4.2.9 on 2024-01-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_applications', '0007_alter_leaveapplication_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
