# Generated by Django 4.2.9 on 2024-01-19 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_cleardatemodel_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='holiday_date',
            field=models.DateField(default=datetime.date(2024, 1, 19)),
        ),
    ]
