# Generated by Django 4.2.9 on 2024-01-19 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_holiday_dateofcreation_alter_holiday_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holiday',
            old_name='holiday_date',
            new_name='date',
        ),
    ]
