# Generated by Django 4.2.9 on 2024-01-19 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_holiday_date_holiday_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
