# Generated by Django 4.2.9 on 2024-01-19 11:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leave_applications', '0001_initial'),
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaveattachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateofcreation', models.DateField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('fileid', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='leaveattachments', to='file_upload.schoolimage')),
                ('leave_application', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaveattachments', to='leave_applications.leaveapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
