# Generated by Django 4.2.9 on 2024-01-19 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateofcreation', models.DateField(auto_now_add=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=utils.file_upload)),
                ('original_file_name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, default='Ttitle', max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('school_id', models.UUIDField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='innovation_document_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
